# Generated by Django 4.1.7 on 2023-02-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meets',
            old_name='creationTime',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='meets',
            old_name='maxCapacity',
            new_name='max_capacity',
        ),
        migrations.RenameField(
            model_name='meets',
            old_name='meetDate',
            new_name='meet_date',
        ),
        migrations.RenameField(
            model_name='meets',
            old_name='meetName',
            new_name='meet_name',
        ),
        migrations.RenameField(
            model_name='spectators',
            old_name='meetID',
            new_name='meet_id',
        ),
        migrations.RenameField(
            model_name='spectators',
            old_name='purchaseTime',
            new_name='purchase_time',
        ),
        migrations.RenameField(
            model_name='spectators',
            old_name='seatNum',
            new_name='seat_num',
        ),
        migrations.RenameField(
            model_name='spectators',
            old_name='SpectatorFname',
            new_name='spectator_fname',
        ),
        migrations.RenameField(
            model_name='spectators',
            old_name='SpectatorLname',
            new_name='spectator_lname',
        ),
        migrations.RenameField(
            model_name='spectators',
            old_name='ticketCost',
            new_name='ticket_cost',
        ),
    ]
