# Generated by Django 4.1.7 on 2023-03-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0004_remove_spectators_meet_id_remove_spectators_seat_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectators',
            name='purchase_time',
        ),
    ]
