# Generated by Django 4.1.7 on 2023-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0005_remove_spectators_purchase_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectators',
            name='spectator_country',
            field=models.CharField(default='United States', max_length=40),
        ),
        migrations.AlterField(
            model_name='spectators',
            name='spectator_state',
            field=models.CharField(default='MD', max_length=2),
        ),
    ]
