# Generated by Django 4.1.7 on 2023-04-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0006_alter_spectators_spectator_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectators',
            name='spectator_country',
        ),
    ]
