# Generated by Django 4.1.7 on 2023-04-11 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0007_remove_spectators_spectator_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectators',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='spectators',
            name='ticket_cost',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
