# Generated by Django 4.1.7 on 2023-04-11 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0008_spectators_purchase_time_spectators_ticket_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectators',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 14, 43, 34, 214187, tzinfo=datetime.timezone.utc)),
        ),
    ]
