# Generated by Django 4.1.7 on 2023-04-18 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0009_alter_spectators_purchase_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectators',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 14, 52, 8, 874994, tzinfo=datetime.timezone.utc)),
        ),
    ]
