# Generated by Django 4.1.7 on 2023-08-03 01:36

import Event_Ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0009_alter_spectators_purchase_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meets',
            name='meet_about_text',
            field=models.TextField(default='Please add a paragraph about the meet.', max_length=1200),
        ),
        migrations.AddField(
            model_name='meets',
            name='meet_location_address',
            field=models.CharField(default='123 Broderick Ln', max_length=75),
        ),
        migrations.AddField(
            model_name='meets',
            name='meet_location_city',
            field=models.CharField(default='Columbia', max_length=75),
        ),
        migrations.AddField(
            model_name='meets',
            name='meet_location_state',
            field=models.CharField(default='MD', max_length=2),
        ),
        migrations.AddField(
            model_name='meets',
            name='meet_location_venue',
            field=models.CharField(default='Chiseled Life', max_length=75),
        ),
        migrations.AddField(
            model_name='meets',
            name='meet_location_zipcode',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='meets',
            name='meet_time_start',
            field=models.CharField(default='00:00', max_length=5, validators=[Event_Ticketing.models.validate_time_format]),
        ),
    ]
