# Generated by Django 4.1.7 on 2023-08-31 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0010_meets_meet_about_text_meets_meet_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectators',
            name='meets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Event_Ticketing.meets'),
        ),
        migrations.AlterField(
            model_name='spectators',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
