# Generated by Django 4.1.7 on 2024-03-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0011_spectators_meets_alter_spectators_purchase_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectators',
            name='ticket_cost',
        ),
        migrations.AddField(
            model_name='meets',
            name='ticket_cost',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
