# Generated by Django 4.1.7 on 2023-04-27 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0011_alter_spectators_purchase_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectators',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 13, 7, 35, 208786, tzinfo=datetime.timezone.utc)),
        ),
    ]
