# Generated by Django 5.0.1 on 2024-06-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0012_remove_spectators_ticket_cost_meets_ticket_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectators',
            name='meets',
        ),
    ]
