# Generated by Django 5.0.1 on 2024-06-18 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Ticketing', '0013_remove_spectators_meets'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectators',
            name='meets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Event_Ticketing.meets'),
        ),
    ]
