from django.urls import path, include
from rest_framework import routers
from .views import HomeViewSet

# register viewset as restful endpoints
router = routers.DefaultRouter()
router.register(r'', HomeViewSet)

# app name for main prject urls.py file
app_name = 'events'

#includes urls generated by the router
urlpatterns = [
    # future views added later
]

urlpatterns += router.urls