from django.urls import path, include
from rest_framework import routers
from .views import HomeViewSet
from .views import CreateSpectatorView
from .views import create_payment_intent
from .views import SubmitMeetForm
from . import views

# register viewset as restful endpoints
router = routers.DefaultRouter()
# router.register(r'home_page', HomeViewSet, basename='home_page')
# router.register(r'add-spectator', CreateSpectatorView)

# app name for main project urls.py file
app_name = 'events'

#includes urls generated by the router
urlpatterns = [
    # future views added later
    path('home_page/', HomeViewSet.as_view(), name='home_page'),
    path('add_spectator/', CreateSpectatorView.as_view(), name='add_spectator'),
    path('create-payment-intent/', create_payment_intent, name='create_payment_intent'),
    path('add_meet/', SubmitMeetForm.as_view(), name='add_meet'),
]

urlpatterns += router.urls