from django.urls import path, include
from rest_framework import routers
from .views import HomeViewSet
from .views import CreateSpectatorView
from . import views

# register viewset as restful endpoints
router = routers.DefaultRouter()
router.register(r'', HomeViewSet)
# router.register(r'add-spectator', CreateSpectatorView)

# app name for main prject urls.py file
app_name = 'events'

#includes urls generated by the router
urlpatterns = [
    # future views added later
    path('add_spectator/', CreateSpectatorView.as_view(), name='add_spectator'),
]

urlpatterns += router.urls